<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE alumnos [

   <!ELEMENT alumnos (nuevos)*>

   <!ELEMENT nuevos (nombre, primerapellido, segundoapellido)>

   <!ELEMENT nombre (#PCDATA)>

   <!ELEMENT primerapellido (#PCDATA)>

   <!ELEMENT segundoapellido (#PCDATA)>

]>

<alumnos>

   <nuevos>

      <nombre>Juan</nombre>

      <primerapellido>Blanco</primerapellido>

      <segundoapellido>Peral</segundoapellido>

   </nuevos>

   <alumnos>

   <nuevos>

      <nombre>Ana</nombre>

      <primerapellido>Vega</primerapellido>

      <segundoapellido>Luz</segundoapellido>

   </nuevos>

   <alumnos>

   <nuevos>

      <nombre>Noelia</nombre>

      <primerapellido>Cano</primerapellido>

      <segundoapellido>Esera</segundoapellido>

   </nuevos>

</alumnos>